# Generated by Django 6.0.6 on 2026-09-06 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('entry_grade', models.CharField(choices=[('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], max_length=2)),
                ('parent_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], max_length=50)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('home_address', models.TextField()),
                ('previous_school', models.CharField(max_length=200)),
                ('current_grade', models.CharField(blank=True, max_length=50)),
                ('report_card', models.FileField(blank=True, null=True, upload_to='report_cards/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('confirm_accurate', models.BooleanField(default=False)),
                ('confirm_policy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
