# Generated by Django 6.1.1 on 2026-09-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0002_studentapplication_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='entry_grade',
            field=models.CharField(choices=[('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11')], max_length=2),
        ),
    ]
